 
DROP TABLE IF EXISTS RECORDS_X_AUTHOR;
CREATE TABLE RECORDS_X_AUTHOR(
  authorName VARCHAR(250) PRIMARY KEY,
  recordNum INT NOT NULL
);


DROP TABLE IF EXISTS RECORDS_X_ORCID_AUTHOR;
CREATE TABLE RECORDS_X_ORCID_AUTHOR(
  authorORCID VARCHAR(250) PRIMARY KEY,
  recordNum INT NOT NULL
);



DROP TABLE IF EXISTS RECORDS_X_PUBLICATION_YEAR;
CREATE TABLE RECORDS_X_PUBLICATION_YEAR(
  publicationYear INT PRIMARY KEY,
  recordNum INT NOT NULL
);



DROP TABLE IF EXISTS RECORDS_X_TYPOLOGY;
CREATE TABLE RECORDS_X_TYPOLOGY(
  typology VARCHAR(250) PRIMARY KEY,
  recordNum INT NOT NULL
);


DROP TABLE IF EXISTS RECORDS_JOURNALS_X_PUBLICATION_YEAR;
CREATE TABLE RECORDS_JOURNALS_X_PUBLICATION_YEAR(
  publicationYear INT PRIMARY KEY,
  recordNum INT NOT NULL
);
